FROM python:3.11

COPY /src /src
COPY /requirements /requirements
COPY /unittests /unittests

RUN pip install -r ./requirements/dev.txt
RUN pip install -r ./requirements/test.txt

ENTRYPOINT ["python", "-m", "pytest", "--cov=src", "unittests/"]